blog/config/routes.rb
Rails.application.routes.draw do
  resources :users

  get 'welcome/index'
  root :to => 'welcome#index'

  resources :articles do 
    resources :comments, shallow: true 
  end

end

blog/app/models/article.rb
class Article < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: {minimum: 5}
end

blog/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  validates :body, presence: true
end

blog/app/models/user.rb
class User < ActiveRecord::Base
end

blog/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blog/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  http_basic_authenticate_with name: "dhh", password: "secret", only: [:destroy]
  
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create

    #render plain: params
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end

  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    if @article.destroy
      redirect_to articles_path
    end
  end


  private
  def article_params
    params.require(:article).permit(:title, :text)
  end



end

blog/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
  end


  def create
    @article = Article.find(params[:article_id])
    #@articles = Article.all
    @comment = @article.comments.build(comment_params)
    if @comment.save
      redirect_to article_path(@article)
    else
      @article.comments.destroy(@comment)
      render 'articles/show'
      #render :template => 'articles/show'
    end
  end

  def edit
  end

  def update
  end

  def destroy

    @article = Article.find(params[:article_id])
    @comment = Comment.find(params[:id])
    if @comment.destroy
      redirect_to article_path(@article) 
    else
    end

  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end

end

blog/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

blog/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

blog/app/helpers/application_helper.rb
module ApplicationHelper
end

blog/app/helpers/articles_helper.rb
module ArticlesHelper
end

blog/app/helpers/comments_helper.rb
module CommentsHelper
end

blog/app/helpers/users_helper.rb
module UsersHelper
end

blog/app/helpers/welcome_helper.rb
module WelcomeHelper
end

blog/app/views/articles/_comment.html.erb
  <p>
    <strong>Commenter:</strong>
    <%= comment.commenter %>
  </p>
 
  <p>
    <strong>Comment:</strong>
    <%= comment.body %>
  </p>

  <p>
    <%= link_to 'Destroy Comment', comment_path(comment, :article_id=>@article), :method=> :delete %>
  </p>

blog/app/views/articles/_form.html.erb
  <%if @article.errors.any?%>
    <div id = "error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li> <%= msg %></li>
        <% end%>
      </ul>
    </div>
  <%end%>

  <p>
    <%=f.label :title %><br>
    <%=f.text_field :title %>
  </p>

  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text%>
  </p>

  <p>
    <%= f.submit %>
  </p>

blog/app/views/articles/edit.html.erb
<h1>EDIT Atriticle</h1>

<%= form_for @article, :url => article_path(@article), :method=> :PUT do |f|%>
  <%= render(:partial=>'form', :locals=>{:f => f})%>
<%end%>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/index.html.erb
<h1>Index</h1>


<h1>Listing articles</h1>
<%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to('Show', article_path(article)) %></td>
      <td><%= link_to('Edit', edit_article_path(article)) %></td>
      <td><%= link_to('Delete', article_path(article), :method=>:delete, data: { confirm: 'Are you sure?' })%></td>
    </tr>
  <% end %>
</table>

blog/app/views/articles/new.html.erb
<h1>NEW Atriticle</h1>

<%= form_for @article, :url => articles_path do |f|%>
  
  <%= render(:partial=>'form', :locals=>{:f => f})%>

<%end%>

<%= link_to 'Back', articles_path %>

blog/app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>



<h2>Comments</h2>
<%= render partial: "articles/comment" , :collection=> @article.comments, :as=> :comment %>



<h2>Add a comment:</h2>
<%= form_for(:comment, :url=> article_comments_path(@article, @article.comments.build)) do |f| %>
  
  <%= render :partial=>"comments/form", :locals=>{:f=>f}%>

<% end %>

<%= link_to 'Back', articles_path%>
| <%= link_to 'Edit', edit_article_path(@article) %>

blog/app/views/comments/_form.html.erb
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>

blog/app/views/comments/index.html.erb
<h1>This is comments index</h1>

blog/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

blog/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

blog/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

blog/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

blog/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

blog/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

blog/app/views/welcome/index.html.erb
<h1>Hello rails newbie</h1>